### ISSUE TITLE
Migrate code coverage tool from `c8` to `codecov`

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/dwn-sdk-js#534]
### Background:
We currently use `c8` as the code coverage tool, while it is useful to see the coverage as we run tests locally on the command-line terminal, it would be great to also add a tool that does CICD integration.

### Task Details:
Integrate `codecov` with our CICD.

A couple of min-bar requirements that comes to mind:

- [ ] The README.md shows the latest updated code coverage numbers.
- [ ] Showing code coverage delta/difference for each submitted PR.
- [ ] Have a customized `codecov.yml` tailored to our needs:
    1. Require 100% coverage on new code
    1. Require coverage to never drop
    1. Exclude interface/type files if needed
    
Example (incomplete) snippet of `codecov.yml`:

```yaml
component_management:
  default_rules:
    statuses:
      - type: project
        target: auto # auto compares coverage to the previous base commit
        threshold: 0% # do not allow coverage drop from the previous base commit coverage
      - type: patch
        target: 100 # all new code should be tested 
```

There is a precedence that we can follow in [`web5-js` repo](https://github.com/TBD54566975/web5-js#web5-js-sdk), you can probably locate the PR/commit in its commit history and copy the pattern/code from there.

## Picking Up This Issue:
- If you'd like to work on this, please comment "picking this up" below, and I'll assign the issue to you 

## Questions:
- If you need assistance or clarification, feel free to comment below.
- Feeling overwhelmed? Join our [`#hack-together` channel](https://discord.gg/tbd) and collaborate with a buddy.
- New to open-source? Check out our [Hacktober `#getting-started` channel](https://discord.gg/tbd).
- [Leaderboard](https://github.com/TBD54566975/developer.tbd.website/issues/721): Check your ranking after finishing this task.

### Resources:
- **Creating a Pull Request**: If you're new to GitHub and unsure how to create a pull request, follow this [step-by-step guide](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Remember, communication is key! If you have any questions or face any challenges, we're here to help so please don't hesitate to reach out.

Good Luck! 🍁

**Comment by EbonyLouis** [comment]
@0scvr, I've assigned it to you! 🥳 Reach out if you need any help at all.

**Comment by thehenrytsai** [comment]
@0scvr, no strong opinion, you can leave it in the `integrity-check.yml` as long as it is not hard to read and does what's intended.

**Comment by 0scvr** [comment]
Correct me if I'm wrong, but this issue should be fixed now.

**Comment by thehenrytsai** [comment]
@0scvr you are right. Closing.
